### PR TITLE
Update deprecated redirection

### PR DESCRIPTION
**Pull request by Brottweiler**
https://github.com/fish-shell/fish-shell/issues/8105#issuecomment-873448774

### CODE REVIEW

**Comment by niladam** [comment]
Thank you for this!:)

**Comment by jvast** [comment]
I wish I'd checked this PR out - I was about to submit the same.

**Comment by sjl** [comment]
The hamster wheel of backwards incompatibility strikes again.

**Comment by sjl** [comment]
Merged, thanks.

**Pull request merged**
